#!/usr/bin/env python3
"""Original illustrative graph polylines, authored for the native 108x34 area.

These parametric motifs identify menu choices; they do not classify ODEs by shape.
No solver, external artwork, font, bitmap, or calculator manual is used here.
The checked-in compact C geometry is firmware input. capture_tiles.py exports
PNGs by running that same geometry through the application renderer.
"""
from pathlib import Path
import argparse
import math

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
points, strokes, icons = [], [], []


def stroke(color, fn, count=33):
    start = len(points)
    for i in range(count):
        x, y = fn(i / (count-1))
        p = (int(math.floor(x+.5)), int(math.floor(y+.5)))
        assert 0 <= p[0] < 108 and 0 <= p[1] < 33
        if len(points) == start or p != points[-1]:
            points.append(p)
    strokes.append((start, len(points)-start, color))


for icon in range(8):
    first = len(strokes)
    if icon == 0:  # smooth increasing first-order motif
        stroke(0x001f, lambda t: (8+91*t, 29-25*t*t))
    elif icon == 1:  # damped oscillation
        stroke(0xf800, lambda t: (8+91*t, 17+13*math.exp(-1.7*t)*math.cos(5*math.pi*t)))
    elif icon == 2:  # multiple modal curves
        for color, shift in [(0x001f, 0), (0xf81f, 1.7), (0x03a0, 3.4)]:
            stroke(color, lambda t, s=shift: (8+91*t, 17+11*math.sin(2.2*math.pi*t+s)))
    elif icon == 3:  # phase spiral, compressed only to fit the intended icon box
        stroke(0x001f, lambda t: (54+43*(1-.87*t)*math.cos(5.4*math.pi*t),
                                     17-14*(1-.87*t)*math.sin(5.4*math.pi*t)), 81)
    elif icon == 4:  # separable decay motif
        stroke(0x001f, lambda t: (8+91*t, 29-25*math.exp(-4*t)))
    elif icon == 5:  # linear growth motif
        stroke(0xf800, lambda t: (8+91*t, 29-25*t))
    elif icon == 6:  # nonlinear saturation motif
        stroke(0xf81f, lambda t: (8+91*t, 30-27/(1+math.exp(-9*(t-.5)))))
    else:  # general nonmonotone motif
        stroke(0x001f, lambda t: (8+91*t, 18+10*math.cos(3.5*math.pi*t)*math.exp(-.7*t)))
    icons.append((first, len(strokes)-first))

text = '/* Generated by tools/generate_menu_icons.py; original menu geometry. */\n'
text += 'static const unsigned char icon_points[][2]={\n'
for j in range(0, len(points), 8):
    text += '    '+','.join('{%d,%d}' % p for p in points[j:j+8])+',\n'
text += '};\nstatic const struct {unsigned short offset,count,color;} icon_strokes[]={\n'
text += ''.join('    {%d,%d,0x%04x},\n' % s for s in strokes)
text += '};\nstatic const unsigned char icon_ranges[8][2]={\n'
text += ''.join('    {%d,%d},\n' % p for p in icons)+'};\n'
target = root/'src/ui/menu_icons.inc'
if args.check:
    assert target.read_text() == text
else:
    target.write_text(text)
print(f'8 original icons: {len(points)} coordinate pairs, {len(strokes)} strokes, '
      f'{len(points)*2+len(strokes)*6+16} bytes of const geometry.')
